<?php
/** @var Oggetto_Payment_Block_Standard $this */
?>
<form name="payment_form" method="post" action="<?php echo $this->getGatewayUrl(); ?>">
    <?php foreach ($this->getFields() as $_field => $_value): ?>
        <input type="hidden" name="<?php echo $_field; ?>" value="<?php echo $_value; ?>">
    <?php endforeach; ?>
</form>
<script type="text/javascript">
    document.payment_form.submit();
</script>