<?php
/** @var Mage_Core_Block_Template $this */

/** @var Oggetto_Payment_Helper_Data $_helper */
$_helper = $this->helper('oggettopayment');
?>
<form name="payment_form" method="post" action="<?php echo $_helper->getGatewayUrl(); ?>">
    <?php foreach ($_helper->getFields() as $_field => $_value): ?>
        <input type="hidden" name="<?php echo $_field; ?>" value="<?php echo $_value; ?>">
    <?php endforeach; ?>
</form>
<script type="text/javascript">
    document.payment_form.submit();
</script>